### ISSUE TITLE
error with poetry run manage.py migrate

### ISSUE THREAD

**Issue by NicolettaK** [ziotom78/instrumentdb#36]
Hi, 

@ziotom78 I'm trying to install this following your instructions.
But I got stuck after `poetry run manage.py migrate` with the following error...

```
(base) niki@mowgli:~/Library/LiteBIRD/instrumentdb$ poetry run manage.py migrate
Traceback (most recent call last):
  File "/Users/niki/Library/Caches/pypoetry/virtualenvs/instrumentdb-hzqnnxEL-py3.8/lib/python3.8/site-packages/django/db/backends/base/base.py", line 220, in ensure_connection
    self.connect()
  File "/Users/niki/Library/Caches/pypoetry/virtualenvs/instrumentdb-hzqnnxEL-py3.8/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/Users/niki/Library/Caches/pypoetry/virtualenvs/instrumentdb-hzqnnxEL-py3.8/lib/python3.8/site-packages/django/db/backends/base/base.py", line 197, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/Users/niki/Library/Caches/pypoetry/virtualenvs/instrumentdb-hzqnnxEL-py3.8/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/Users/niki/Library/Caches/pypoetry/virtualenvs/instrumentdb-hzqnnxEL-py3.8/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 199, in get_new_connection
    conn = Database.connect(**conn_params)
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/niki/Library/Caches/pypoetry/virtualenvs/instrumentdb-hzqnnxEL-py3.8/bin/manage", line 11, in <module>
    load_entry_point('instrumentdb', 'console_scripts', 'manage')()
  File "/Users/niki/Library/LiteBIRD/instrumentdb/manage.py", line 19, in main
    execute_from_command_line(sys.argv)
  File "/Users/niki/Library/Caches/pypoetry/virtualenvs/instrumentdb-hzqnnxEL-py3.8/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/Users/niki/Library/Caches/pypoetry/virtualenvs/instrumentdb-hzqnnxEL-py3.8/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/niki/Library/Caches/pypoetry/virtualenvs/instrumentdb-hzqnnxEL-py3.8/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/niki/Library/Caches/pypoetry/virtualenvs/instrumentdb-hzqnnxEL-py3.8/lib/python3.8/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/Users/niki/Library/Caches/pypoetry/virtualenvs/instrumentdb-hzqnnxEL-py3.8/lib/python3.8/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/Users/niki/Library/Caches/pypoetry/virtualenvs/instrumentdb-hzqnnxEL-py3.8/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 86, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/Users/niki/Library/Caches/pypoetry/virtualenvs/instrumentdb-hzqnnxEL-py3.8/lib/python3.8/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/Users/niki/Library/Caches/pypoetry/virtualenvs/instrumentdb-hzqnnxEL-py3.8/lib/python3.8/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/Users/niki/Library/Caches/pypoetry/virtualenvs/instrumentdb-hzqnnxEL-py3.8/lib/python3.8/site-packages/django/db/migrations/loader.py", line 212, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/Users/niki/Library/Caches/pypoetry/virtualenvs/instrumentdb-hzqnnxEL-py3.8/lib/python3.8/site-packages/django/db/migrations/recorder.py", line 76, in applied_migrations
    if self.has_table():
  File "/Users/niki/Library/Caches/pypoetry/virtualenvs/instrumentdb-hzqnnxEL-py3.8/lib/python3.8/site-packages/django/db/migrations/recorder.py", line 56, in has_table
    return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
  File "/Users/niki/Library/Caches/pypoetry/virtualenvs/instrumentdb-hzqnnxEL-py3.8/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/Users/niki/Library/Caches/pypoetry/virtualenvs/instrumentdb-hzqnnxEL-py3.8/lib/python3.8/site-packages/django/db/backends/base/base.py", line 260, in cursor
    return self._cursor()
  File "/Users/niki/Library/Caches/pypoetry/virtualenvs/instrumentdb-hzqnnxEL-py3.8/lib/python3.8/site-packages/django/db/backends/base/base.py", line 236, in _cursor
    self.ensure_connection()
  File "/Users/niki/Library/Caches/pypoetry/virtualenvs/instrumentdb-hzqnnxEL-py3.8/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/Users/niki/Library/Caches/pypoetry/virtualenvs/instrumentdb-hzqnnxEL-py3.8/lib/python3.8/site-packages/django/db/backends/base/base.py", line 220, in ensure_connection
    self.connect()
  File "/Users/niki/Library/Caches/pypoetry/virtualenvs/instrumentdb-hzqnnxEL-py3.8/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/niki/Library/Caches/pypoetry/virtualenvs/instrumentdb-hzqnnxEL-py3.8/lib/python3.8/site-packages/django/db/backends/base/base.py", line 220, in ensure_connection
    self.connect()
  File "/Users/niki/Library/Caches/pypoetry/virtualenvs/instrumentdb-hzqnnxEL-py3.8/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/Users/niki/Library/Caches/pypoetry/virtualenvs/instrumentdb-hzqnnxEL-py3.8/lib/python3.8/site-packages/django/db/backends/base/base.py", line 197, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/Users/niki/Library/Caches/pypoetry/virtualenvs/instrumentdb-hzqnnxEL-py3.8/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/Users/niki/Library/Caches/pypoetry/virtualenvs/instrumentdb-hzqnnxEL-py3.8/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 199, in get_new_connection
    conn = Database.connect(**conn_params)
django.db.utils.OperationalError: unable to open database file
```

**Comment by ziotom78** [comment]
This typically happens when the directory you specified in your `.env` file (key `STORAGE_PATH`) does not exist. Is this the case? If it's so, you should create it first and then issue the `migrate` command.

**Comment by NicolettaK** [comment]
ok, sorry! now it worked!
